### ISSUE TITLE
test

### ISSUE THREAD

**Issue by mkizka** [mkizka/pdsadmin-web#17]

**Comment by mkizka** [comment]
@claude claude.ymlを修正して、`@claude`でGitHub Actionsを呼び出したときに、呼び出したそのコメントにemojiで :eyes: リアクションをするようにして

**Comment by mkizka** [comment]
@claude 許可されているはずですが、追加設定が必要なら教えて
```
      - name: Run Claude Code
        id: claude
        uses: anthropics/claude-code-action@beta
        with:
          anthropic_api_key: ${{ secrets.ANTHROPIC_API_KEY }}
          allowed_tools: "Bash(pnpm i),Bash(pnpm build),Bash(pnpm typecheck),Bash(pnpm lint),Bash(pnpm format),Bash(pnpm setup-dev-env),Bash(pnpm e2e)"
          timeout_minutes: 5
```

```
[
  {
    "type": "system",
    "subtype": "init",
    "session_id": "03659cd5-7879-4940-90b7-7dcf83365d5c",
    "tools": [
      "Task",
      "Bash",
      "Glob",
      "Grep",
      "LS",
      "Read",
      "Edit",
      "MultiEdit",
      "Write",
      "NotebookRead",
      "NotebookEdit",
      "TodoRead",
      "TodoWrite",
      "mcp__github_file_ops__commit_files",
      "mcp__github_file_ops__delete_files",
      "mcp__github__add_issue_comment",
      "mcp__github__add_pull_request_review_comment",
      "mcp__github__create_branch",
      "mcp__github__create_issue",
      "mcp__github__create_or_update_file",
      "mcp__github__create_pull_request",
      "mcp__github__create_pull_request_review",
      "mcp__github__create_repository",
      "mcp__github__delete_file",
      "mcp__github__fork_repository",
      "mcp__github__get_code_scanning_alert",
      "mcp__github__get_commit",
      "mcp__github__get_file_contents",
      "mcp__github__get_issue",
      "mcp__github__get_issue_comments",
      "mcp__github__get_me",
      "mcp__github__get_pull_request",
      "mcp__github__get_pull_request_comments",
      "mcp__github__get_pull_request_files",
      "mcp__github__get_pull_request_reviews",
      "mcp__github__get_pull_request_status",
      "mcp__github__get_secret_scanning_alert",
      "mcp__github__get_tag",
      "mcp__github__list_branches",
      "mcp__github__list_code_scanning_alerts",
      "mcp__github__list_commits",
      "mcp__github__list_issues",
      "mcp__github__list_pull_requests",
      "mcp__github__list_secret_scanning_alerts",
      "mcp__github__list_tags",
      "mcp__github__merge_pull_request",
      "mcp__github__push_files",
      "mcp__github__search_code",
      "mcp__github__search_issues",
      "mcp__github__search_repositories",
      "mcp__github__search_users",
      "mcp__github__update_issue",
      "mcp__github__update_issue_comment",
      "mcp__github__update_pull_request",
      "mcp__github__update_pull_request_branch",
      "mcp__github__update_pull_request_comment"
    ],
    "mcp_servers": [
      {
        "name": "github_file_ops",
        "status": "connected"
      },
      {
        "name": "github",
        "status": "connected"
      }
    ]
  },
```
